test the service is up in kubernentes

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -132,6 +132,47 @@ deploy-to-kubernetes:
     gke-cluster-zone: $GKE_CLUSTER_ZONE
     gke-cluster-project: $GKE_CLUSTER_PROJECT
     command: apply -f $WERCKER_OUTPUT_DIR/kubernetes/
+  - script:
+        name: wait for kubernetes to start the services
+        code: |
+          sleep 20
+  - riceo/kubectl:
+    name: make sure the deployment is up
+    server: $KUBERNETES_MASTER
+    gcloud-key-json: $GCR_JSON_KEY_FILE
+    gke-cluster-name: $GKE_CLUSTER_NAME
+    gke-cluster-zone: $GKE_CLUSTER_ZONE
+    gke-cluster-project: $GKE_CLUSTER_PROJECT
+    command: get deploy api-${WERCKER_GIT_BRANCH}
+  - riceo/kubectl:
+    name: make sure the service is up
+    server: $KUBERNETES_MASTER
+    gcloud-key-json: $GCR_JSON_KEY_FILE
+    gke-cluster-name: $GKE_CLUSTER_NAME
+    gke-cluster-zone: $GKE_CLUSTER_ZONE
+    gke-cluster-project: $GKE_CLUSTER_PROJECT
+    command: get service api-${WERCKER_GIT_BRANCH}
+  - riceo/kubectl:
+    name: make sure the service is up
+    server: $KUBERNETES_MASTER
+    gcloud-key-json: $GCR_JSON_KEY_FILE
+    gke-cluster-name: $GKE_CLUSTER_NAME
+    gke-cluster-zone: $GKE_CLUSTER_ZONE
+    gke-cluster-project: $GKE_CLUSTER_PROJECT
+    raw-args: >/tmp/kube_tag_${WERCKER_GIT_BRANCH}
+    command: get -o template deploy api-${WERCKER_GIT_BRANCH} --template={{.metadata.labels.commit}}
+  - script:
+        name: test the deployment is up with the right commit
+        code: |
+          DEPLOYED_COMMIT=$(<file/tmp/kube_tag_${WERCKER_GIT_BRANCH})
+          if [ "$DEPLOYED_COMMIT" == "${WERCKER_GIT_COMMIT}" ]
+            then
+              echo "deployment up"
+            else
+              echo -e "ERROR: wrong commit is deployed"$DEPLOYED_COMMIT
+              exit 1
+            fi
+
 
 
 #deploy:
